---
- name: ensure ranger is installed
  apt:
    name: "{{ [ranger_package_name] + ranger_shared_packages + ranger_exclusive_packages }}"
    state: present

- name: ensure ranger python packages are installed
  apt:
    name: "{{ ranger_python2_packages + ranger_python3_packages }}"
    state: present
