---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    - name: ensure git exists
      apt:
        name: git
        state: present

  tasks:
    - name: "Include ansible-role-ranger"
      include_role:
        name: "ansible-role-ranger"
